on: [push]

jobs:
  cprepo-dogfood:
    runs-on: ubuntu-latest
    name: Dogfood cprepo GitHub action
    steps:
    - uses: actions/checkout@v2
    - name: copy test
      uses: ./
      with:
        src-path: 'foo.txt'
        dst-path: 'foobar.txt'
