on: [push]

jobs:
  cprepo-dogfood:
    runs-on: ubuntu-latest
    name: dogfood cprepo action
    steps:
    - uses: actions/checkout@v2
    - name: setup test files
      run: |
        mkdir test-src test-dst
        printf "a\nb\nc\n" > test-src/test1.txt

        printf "a\nb\nc\nd\n" > test-src/test2.txt
        printf "a\nb\nc\n" > test-dst/test2.txt

        printf "a\nb\nc\n" > test-src/test3.txt
        printf "a\nb\nc\n" > test-dst/test3.txt

    - name: 'copy test 1: destination file does not exist'
      id: test-1
      uses: ./
      with:
        src-path: test-src/test1.txt
        dst-path: test-dst/test1.txt
    - name: 'verify test 1'
      run: |
        diff test-src/test1.txt test-dst/test1.txt
        echo "changed =  ${{ steps.test-1.outputs.changed }}"

    - name: 'copy test 2: files differ'
      uses: ./
      with:
        src-path: test-src/test2.txt
        dst-path: test-dst/test2.txt
    - name: 'verify test 2'
      run: diff test-src/test2.txt test-dst/test2.txt

    - name: 'copy test 3: files same'
      uses: ./
      with:
        src-path: test-src/test3.txt
        dst-path: test-dst/test3.txt
    - name: 'verify test 3'
      run: diff test-src/test3.txt test-dst/test3.txt

    - name: 'copy test 4: different file names'
      uses: ./
      with:
        src-path: test-src/test3.txt
        dst-path: test-dst/test4.txt
    - name: 'verify test 4'
      run: diff test-src/test3.txt test-dst/test4.txt