on: [push]

jobs:
  cprepo-dogfood:
    runs-on: ubuntu-latest
    name: Dogfood cprepo GitHub action
    steps:
    - uses: actions/checkout@v2
    - name: setup test files
      run: |
        mkdir test-src test-dst
        printf "a\nb\nc\n" > test-src/test1.txt
        printf "a\nb\nc\nd\n" > test-src/test2.txt
    - name: 'copy test, destination file does not exist'
      uses: ./
      with:
        src-path: test-src/test1.txt
        dst-path: test-dst/test1.txt
    - name: verify
      run: diff test-src/test1.txt test-dst/test2.txt